apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: yordle-backend
    spec:
      containers:
      - name: backend
        image: {{ include "backend-image" . }}
        imagePullPolicy: Always
        entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0"]
        ports:
        - containerPort: {{ .Values.port }}
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.port }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.port }}
        resources:
{{ toYaml .Values.resources | indent 10 }}